-- Item 1 — line identity schema fix.
--
-- Today a line is identified by a plain text `line_slug` in three tables with
-- no foreign key. Renaming a slug (which the Earn/Save/Spend reorder will do
-- for real) silently orphans every historical row keyed to the old value —
-- including the pilot's pre/post test results, which are the platform's only
-- evidence of learning gain. Nothing errors; the rows just stop matching.
--
-- This separates identity (lines.id — stable, never changes) from display and
-- routing (slug, title_zh, sort_order — all mutable). Dependent tables
-- reference the id, so a rename or reorder touches exactly one row.
--
-- PHASE 1 OF 2 — "expand". This migration is deliberately safe to run against
-- the live database WHILE THE CURRENT APP IS STILL SERVING. line_id is added
-- NULLABLE, so the existing code, which knows nothing about it, keeps writing
-- successfully and simply leaves the column null on new rows.
--
-- Do NOT add NOT NULL here. Tested: with NOT NULL set at this stage, every
-- insert the current app makes fails outright —
--   ERROR: null value in column "line_id" ... violates not-null constraint
-- on simulation_runs, line_tests and class_rooms alike. On a live pilot that
-- means a student's result is rejected at the moment they submit it. Losing
-- work that way is worse than a column that is briefly null.
--
-- Phase 2 (migration-09) re-backfills anything written during the gap and
-- then applies NOT NULL, once the app dual-writes.
--
-- ADDITIVE AND REVERSIBLE. No row is dropped, truncated, or rewritten.
-- `line_slug` is deliberately kept as a safety net; see the transition note at
-- the bottom before changing application writes.
--
-- Run once, in a transaction, AFTER taking a backup. Reverse:
-- migration-08-lines-identity-down.sql

begin;

-- lines ---------------------------------------------------------------------
-- id is a surrogate key with no relationship to slug or title, so neither can
-- drag identity with it when they change. Seeded explicitly rather than by
-- insert order so the same ids appear in every environment.
create table if not exists public.lines (
  id         integer primary key generated by default as identity,
  slug       text    not null unique,
  title_zh   text    not null,
  sort_order integer not null,
  active     boolean not null default true,
  created_at timestamptz not null default now()
);

comment on column public.lines.id is
  'Stable identity. Never changes for the life of a line, even if the line is renamed, reordered, or reframed into a different topic. All other tables reference this.';
comment on column public.lines.slug is
  'Mutable. Routing and display only (/line/<slug>). Safe to rename.';

-- Seed the ten live lines at their current slugs, so the backfill join below
-- is exact. sort_order mirrors today's display order.
insert into public.lines (id, slug, title_zh, sort_order) values
  (1,  'qixin',    '起薪線', 1),
  (2,  'cunqian',  '存錢線', 2),
  (3,  'xinyong',  '信用線', 3),
  (4,  'touzi',    '投資線', 4),
  (5,  'zhapian',  '詐騙線', 5),
  (6,  'xuedai',   '學貸線', 6),
  (7,  'baoshui',  '報稅線', 7),
  (8,  'zuwu',     '租屋線', 8),
  (9,  'baoxian',  '保險線', 9),
  (10, 'chuangye', '創業線', 10)
on conflict (id) do nothing;

-- Keep the identity sequence ahead of the seeded ids so future inserts
-- (the new 職涯與收入 line) do not collide.
select setval(
  pg_get_serial_sequence('public.lines', 'id'),
  (select max(id) from public.lines)
);

-- line_id on dependent tables -----------------------------------------------
-- Added nullable first. Backfilled. Only then made NOT NULL — so a row that
-- fails to match fails loudly here rather than becoming a silent orphan later.
--
-- ON UPDATE CASCADE is belt-and-braces: ids never change by design, but if one
-- ever did, dependents follow rather than dangle.
-- ON DELETE RESTRICT makes deleting a line with history an error, not a
-- cascade that destroys it.

alter table public.simulation_runs add column if not exists line_id integer;
alter table public.line_tests      add column if not exists line_id integer;
alter table public.class_rooms     add column if not exists line_id integer;

update public.simulation_runs r set line_id = l.id
  from public.lines l where l.slug = r.line_slug and r.line_id is null;
update public.line_tests t set line_id = l.id
  from public.lines l where l.slug = t.line_slug and t.line_id is null;
update public.class_rooms c set line_id = l.id
  from public.lines l where l.slug = c.line_slug and c.line_id is null;

-- Abort the whole migration if any EXISTING row failed to match a seeded
-- slug. At this point nothing has been written by the un-updated app yet, so
-- every row present must resolve; one that doesn't means an unexpected slug
-- is in the data and we want to know before committing, not after.
do $$
declare
  missing_runs  integer;
  missing_tests integer;
  missing_rooms integer;
begin
  select count(*) into missing_runs  from public.simulation_runs where line_id is null;
  select count(*) into missing_tests from public.line_tests      where line_id is null;
  select count(*) into missing_rooms from public.class_rooms     where line_id is null;

  if missing_runs > 0 or missing_tests > 0 or missing_rooms > 0 then
    raise exception
      'Backfill incomplete — simulation_runs: %, line_tests: %, class_rooms: %. Some line_slug value has no matching row in lines. Nothing has been committed.',
      missing_runs, missing_tests, missing_rooms;
  end if;
end $$;

-- NOT NULL is deliberately NOT applied here. See the header. It lands in
-- migration-09, after the app dual-writes.

alter table public.simulation_runs
  add constraint simulation_runs_line_id_fkey foreign key (line_id)
  references public.lines (id) on update cascade on delete restrict;
alter table public.line_tests
  add constraint line_tests_line_id_fkey foreign key (line_id)
  references public.lines (id) on update cascade on delete restrict;
alter table public.class_rooms
  add constraint class_rooms_line_id_fkey foreign key (line_id)
  references public.lines (id) on update cascade on delete restrict;

-- Mirror the existing slug-based indexes on the new key.
create index if not exists simulation_runs_student_line_id_idx
  on public.simulation_runs (student_id, line_id, created_at desc);
create index if not exists line_tests_student_line_id_idx
  on public.line_tests (student_id, line_id, phase, created_at desc);

-- Deprecation markers. These columns stay until the line_id path is proven in
-- production; dropping them is a separate, later change.
comment on column public.simulation_runs.line_slug is
  'DEPRECATED — superseded by line_id. Retained as a safety net. Do not read in new code.';
comment on column public.line_tests.line_slug is
  'DEPRECATED — superseded by line_id. Retained as a safety net. Do not read in new code.';
comment on column public.class_rooms.line_slug is
  'DEPRECATED — superseded by line_id. Retained as a safety net. Do not read in new code.';

alter table public.lines enable row level security;

commit;

-- TRANSITION NOTE — read before changing application writes.
--
-- line_tests.line_slug and class_rooms.line_slug are NOT NULL with no default,
-- and simulation_runs.line_slug defaults to 'qixin'. If the app switches to
-- writing line_id alone, inserts into the first two will fail outright and
-- simulation_runs will silently record every new run as 起薪線.
--
-- So while both columns exist the app must DUAL-WRITE: set line_id and
-- line_slug together on insert, and read line_id only. That keeps the safety
-- net meaningful for new rows too, instead of only for rows written before
-- this migration. Dropping line_slug, and with it the dual write, is the
-- later change that ends the transition.
